name: Deploy US Dev

# on:
#   push:
#     tags:
#       - "dev-us-*"

on:
    push:


env:
    STAGE: Dev
    NEXT_PUBLIC_FORM_SUFFIX: jsagr63434
    DATWIT_RCPT: contact@datwit.com
    DATWIT_FROM: noreply@datwit.com
    LOG_LEVEL: DEBUG
    SITE_REGION: us
    CERTIFICATE_ARN: ${{ vars.CERTIFICATE_ARN }}

jobs:
    deploy-contact-api:
        name: Deploy contact API for Stage
        runs-on: ubuntu-latest
        outputs:
          contact_api_url: ${{ steps.contact_api_url.outputs.CONTACT_API_URL }}
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v4
              with:
                python-version: '3.8'
                cache: 'pip'

            - uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run: |
                npm install -g aws-cdk
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
              working-directory: arch

            - name: Configure AWS credentials from Test account
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - name: Deploy
              run: |
                cdk deploy ${{ env.STAGE }}-ContactAPIStack --require-approval never
              working-directory: arch

            - name: Get Contact API URL
              id: contact_api_url
              run: |
                {
                  echo 'CONTACT_API_URL<<EOF'
                  aws cloudformation describe-stacks \
                      --stack-name ${{ env.STAGE }}-ContactAPIStack \
                      --query "Stacks[0].Outputs[?OutputKey=='ContactApiURL'].OutputValue" \
                      --output text
                  echo EOF
                } >> "$GITHUB_OUTPUT"

    build-web-site:
      runs-on: ubuntu-latest
      needs: [deploy-contact-api]
      steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-node@v4
            with: 
                node-version: 18
                cache: 'npm'
                cache-dependency-path: us/package-lock.json

          - name: Install despendencies
            run: yarn install
            working-directory: us/

          - name: build static site
            env:
                NEXT_PUBLIC_API_URL: ${{ needs.deploy-contact-api.outputs.contact_api_url }}
            run: CI=false yarn build
            working-directory: us/

          - uses: actions/upload-artifact@v3
            with:
              name: website
              path: us/.out

    deploy-web-site:
        runs-on: ubuntu-latest
        needs: [build-web-site]
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v4
              with:
                python-version: '3.8'
                cache: 'pip'

            - uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run: |
                npm install -g aws-cdk
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
              working-directory: arch

            - name: Configure AWS credentials from Test account
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-1

            - uses: actions/download-artifact@v3
              with:
                name: website
                path: arch/static_site

            - name: check files
              run: |
                ls -la arch/static_site

            # - name: Deploy
            #   run: |
            #     cdk deploy ${{ env.STAGE }}-${{ env.SITE_REGION }}-SiteStack --require-approval never
            #   working-directory: arch