name: CI-CD Development

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Upload
        uses: convictional/trigger-workflow-and-wait@1.4.0
        with:
          owner: datwit
          repo: landing3
          github_token: ${{ secrets.LANDING_DEPLOY_TOKEN }}
          workflow_file_name: export_and_upload_to_s3.yml
          ref: development
          wait_interval: 10
          inputs: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true

      - name: Deploy site
        uses: convictional/trigger-workflow-and-wait@1.4.0
        with:
          owner: datwit
          repo: landing-stack
          github_token: ${{ secrets.LANDING_DEPLOY_TOKEN }}
          workflow_file_name: deploy-development.yml
          ref: main
          wait_interval: 10
          inputs: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
