name: Nodejs CI-CD Production

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    env:
      NEXT_PUBLIC_FORM_SUFFIX: hd623ndsu
      NEXT_PUBLIC_API_URL: https://d6tg45n2y3.execute-api.eu-west-1.amazonaws.com/prod/

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.nenvironmentsode-version }}
      
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      
      # remove CI=false in production
      - run: CI=false yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: website
          path: './out'

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    env:
      BUCKET: devstack-staticfiles5266d87b-goeg76g3k7yv
      ASSETS_KEY: prod_landing_assets.zip
    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # download assets to current dir
      - uses: actions/download-artifact@v2
        with:
          name: website

      - name: Push files to bucket
        run: |
          zip -r assets.zip .
          aws s3 cp assets.zip s3://$BUCKET/$ASSETS_KEY
